<?php
namespace grozzzny\soc_link;

use Yii;
use yii\easyii2\models\ModuleEasyii2Interface;

class SocLinkModule extends \yii\easyii2\components\Module implements ModuleEasyii2Interface
{
    public $settings = [
        'modelSocLink' => '\grozzzny\soc_link\models\SocLink',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::registerTranslation();
    }

    public static function registerTranslation()
    {
        Yii::$app->i18n->translations['app/soclink'] = [
            'class' => 'yii\i18n\PhpMessageSource',
            'sourceLanguage' => 'en-US',
            'basePath' => '@grozzzny/soc_link/messages',
            'fileMap' => [
                'app/soclink' => 'soclink.php',
            ],
        ];
    }

    public function getTitle()
    {
        // TODO: Implement getTitle() method.
        return Yii::t('app/soclink', 'Soc. links');
    }

    public function getName()
    {
        // TODO: Implement getName() method.
        return $this->id;
    }

    public function getIcon()
    {
        // TODO: Implement getIcon() method.
        return 'globe';
    }
}