<?php
namespace grozzzny\soc_link\widgets;

use grozzzny\soc_link\models\SocLink;
use grozzzny\soc_link\widgets\assets\SocLinkWidgetAsset;
use yii\base\Widget;
use yii\helpers\Html;

class SocLinkWidget extends Widget
{
    public $options = ['class' => 'soc-link soc-link-default'];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->registerAssets();
    }

    public function run()
    {
        $html = '';

        $html .= Html::beginTag('ul', $this->options);
        foreach (SocLink::find()->all() as $item){
            $html .= Html::beginTag('li');
            $html .= Html::a(
                Html::tag('i', '', ['class' => $item->icon]),
                $item->link,
                ['title' => $item->name]
            );
            $html .= Html::endTag('li');
        }
        $html .= Html::endTag('ul');

        return $html;
    }

    public function registerAssets()
    {
        $view = $this->getView();
        SocLinkWidgetAsset::register($view);
    }
}